# Generated by Django 3.2.5 on 2022-01-20 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_thumbnail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='youtube_app.userprofileinfo'),
        ),
    ]
