# Generated by Django 3.2.5 on 2022-01-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_app', '0002_video_channel_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('commented_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commenter_dp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.userprofileinfo')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_app.video')),
            ],
        ),
    ]
