# Generated by Django 3.2.5 on 2022-01-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0005_videoviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo'),
        ),
    ]
