# Generated by Django 3.2.5 on 2022-01-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0006_alter_userprofileinfo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_photo',
            field=models.ImageField(default='static/round-account-button-with-user-inside_icon-icons.com_72596.png', upload_to='profile_photo'),
        ),
    ]
