# Generated by Django 3.2.5 on 2022-01-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0008_alter_userprofileinfo_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to='cover_photo'),
        ),
    ]
