# Generated by Django 3.2.5 on 2022-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0009_userprofileinfo_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photo'),
        ),
    ]
