# Generated by Django 3.2.5 on 2022-02-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0013_rename_subscriber_date_subscription_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='youtube_app.userprofileinfo'),
        ),
    ]
