# Generated by Django 3.2.5 on 2022-02-04 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_app', '0014_alter_subscription_channel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='channel_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
