# Generated by Django 3.2.5 on 2022-02-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_app', '0015_alter_subscription_channel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel_thumbnail',
        ),
    ]
